# Generated by Django 6.0.4 on 2026-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartspendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='saving_goal',
            field=models.FloatField(default=50000),
        ),
    ]
